export default [
{
  name: 'Barton Watermain City of Hamilton',
  year: 2013,
  images: [{
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-1.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-1.jpg'),
    path: '../images/projects/barton/web/barton-1.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-2.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-2.jpg'),
    path: '../images/projects/barton/web/barton-2.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-3.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-3.jpg'),
    path: '../images/projects/barton/web/barton-3.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-4.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-4.jpg'),
    path: '../images/projects/barton/web/barton-4.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-5.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-5.jpg'),
    path: '../images/projects/barton/web/barton-5.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-6.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-6.jpg'),
    path: '../images/projects/barton/web/barton-6.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-7.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-7.jpg'),
    path: '../images/projects/barton/web/barton-7.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-8.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-8.jpg'),
    path: '../images/projects/barton/web/barton-8.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/barton/web/barton-9.jpg')),
    image: require('image-webpack!../images/projects/barton/web/barton-9.jpg'),
    path: '../images/projects/barton/web/barton-9.jpg',
    sizes: '300w,600w'
  }]
}, {
  name: 'Centennial Parkway City of Hamilton',
  year: 2014,
  images: [{
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-1.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-1.jpg'),
    path: '../images/projects/centennial/web/centennial-1.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-2.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-2.jpg'),
    path: '../images/projects/centennial/web/centennial-2.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-3.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-3.jpg'),
    path: '../images/projects/centennial/web/centennial-3.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-4.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-4.jpg'),
    path: '../images/projects/centennial/web/centennial-4.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-5.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-5.jpg'),
    path: '../images/projects/centennial/web/centennial-5.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-6.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-6.jpg'),
    path: '../images/projects/centennial/web/centennial-6.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-7.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-7.jpg'),
    path: '../images/projects/centennial/web/centennial-7.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-8.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-8.jpg'),
    path: '../images/projects/centennial/web/centennial-8.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/centennial/web/centennial-9.jpg')),
    image: require('image-webpack!../images/projects/centennial/web/centennial-9.jpg'),
    path: '../images/projects/centennial/web/centennial-9.jpg',
    sizes: '300w,600w'
  }]
}, {
  name: 'Derry Road Underpass Region of Halton',
  year: 2014,
  images: [{
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-1.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-1.jpg'),
    path: '../images/projects/derry/web/derry-1.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-10.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-10.jpg'),
    path: '../images/projects/derry/web/derry-10.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-2.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-2.jpg'),
    path: '../images/projects/derry/web/derry-2.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-3.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-3.jpg'),
    path: '../images/projects/derry/web/derry-3.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-4.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-4.jpg'),
    path: '../images/projects/derry/web/derry-4.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-5.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-5.jpg'),
    path: '../images/projects/derry/web/derry-5.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-6.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-6.jpg'),
    path: '../images/projects/derry/web/derry-6.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-7.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-7.jpg'),
    path: '../images/projects/derry/web/derry-7.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-8.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-8.jpg'),
    path: '../images/projects/derry/web/derry-8.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/derry/web/derry-9.jpg')),
    image: require('image-webpack!../images/projects/derry/web/derry-9.jpg'),
    path: '../images/projects/derry/web/derry-9.jpg',
    sizes: '300w,600w'
  }]
}, {
  name: 'King Road Underpass City of Hamilton',
  year: 2013,
  images: [{
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-1.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-1.jpg'),
    path: '../images/projects/king/web/king-1.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-2.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-2.jpg'),
    path: '../images/projects/king/web/king-2.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-3.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-3.jpg'),
    path: '../images/projects/king/web/king-3.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-4.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-4.jpg'),
    path: '../images/projects/king/web/king-4.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-5.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-5.jpg'),
    path: '../images/projects/king/web/king-5.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-6.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-6.jpg'),
    path: '../images/projects/king/web/king-6.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/king/web/king-7.jpg')),
    image: require('image-webpack!../images/projects/king/web/king-7.jpg'),
    path: '../images/projects/king/web/king-7.jpg',
    sizes: '300w,600w'
  }]
}, {
  name: 'TTC York University Station (WALSH)',
  year: 2014,
  images: [{
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-1.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-1.jpg'),
    path: '../images/projects/ttc/web/ttc-1.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-10.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-10.jpg'),
    path: '../images/projects/ttc/web/ttc-10.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-11.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-11.jpg'),
    path: '../images/projects/ttc/web/ttc-11.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-2.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-2.jpg'),
    path: '../images/projects/ttc/web/ttc-2.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-3.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-3.jpg'),
    path: '../images/projects/ttc/web/ttc-3.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-4.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-4.jpg'),
    path: '../images/projects/ttc/web/ttc-4.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-5.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-5.jpg'),
    path: '../images/projects/ttc/web/ttc-5.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-6.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-6.jpg'),
    path: '../images/projects/ttc/web/ttc-6.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-7.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-7.jpg'),
    path: '../images/projects/ttc/web/ttc-7.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-8.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-8.jpg'),
    path: '../images/projects/ttc/web/ttc-8.jpg',
    sizes: '300w,600w'
  }, {
    responsive: JSON.parse(require('image-webpack!resize-image?sizes[]=300w&sizes[]=600w!../images/projects/ttc/web/ttc-9.jpg')),
    image: require('image-webpack!../images/projects/ttc/web/ttc-9.jpg'),
    path: '../images/projects/ttc/web/ttc-9.jpg',
    sizes: '300w,600w'
  }]
}]