export default [
{
  name: 'Barton Watermain City of Hamilton',
  year: 2013,
  images: [{
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-1.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-1.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-1.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-2.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-2.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-2.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-3.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-3.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-3.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-4.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-4.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-4.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-5.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-5.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-5.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-6.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-6.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-6.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-7.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-7.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-7.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-8.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-8.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-8.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/barton/web/barton-9.jpg'),
    image: require('image-webpack!../images/projects/barton/web/barton-9.jpg'),
    path: 'image-webpack!../images/projects/barton/web/barton-9.jpg'
  }]
}, {
  name: 'Centennial Parkway City of Hamilton',
  year: 2014,
  images: [{
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-1.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-1.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-1.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-2.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-2.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-2.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-3.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-3.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-3.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-4.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-4.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-4.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-5.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-5.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-5.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-6.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-6.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-6.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-7.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-7.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-7.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-8.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-8.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-8.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/centennial/web/centennial-9.jpg'),
    image: require('image-webpack!../images/projects/centennial/web/centennial-9.jpg'),
    path: 'image-webpack!../images/projects/centennial/web/centennial-9.jpg'
  }]
}, {
  name: 'Derry Road Underpass Region of Halton',
  year: 2014,
  images: [{
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-1.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-1.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-1.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-10.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-10.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-10.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-2.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-2.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-2.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-3.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-3.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-3.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-4.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-4.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-4.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-5.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-5.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-5.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-6.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-6.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-6.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-7.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-7.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-7.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-8.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-8.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-8.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/derry/web/derry-9.jpg'),
    image: require('image-webpack!../images/projects/derry/web/derry-9.jpg'),
    path: 'image-webpack!../images/projects/derry/web/derry-9.jpg'
  }]
}, {
  name: 'King Road Underpass City of Hamilton',
  year: 2013,
  images: [{
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-1.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-1.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-1.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-2.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-2.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-2.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-3.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-3.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-3.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-4.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-4.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-4.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-5.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-5.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-5.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-6.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-6.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-6.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/king/web/king-7.jpg'),
    image: require('image-webpack!../images/projects/king/web/king-7.jpg'),
    path: 'image-webpack!../images/projects/king/web/king-7.jpg'
  }]
}, {
  name: 'TTC York University Station (WALSH)',
  year: 2014,
  images: [{
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-1.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-1.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-1.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-10.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-10.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-10.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-11.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-11.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-11.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-2.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-2.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-2.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-3.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-3.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-3.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-4.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-4.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-4.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-5.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-5.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-5.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-6.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-6.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-6.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-7.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-7.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-7.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-8.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-8.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-8.jpg'
  }, {
    responsive: require('image-webpack!resize-image?sizes[0]=300w&sizes[1]=600w!../images/projects/ttc/web/ttc-9.jpg'),
    image: require('image-webpack!../images/projects/ttc/web/ttc-9.jpg'),
    path: 'image-webpack!../images/projects/ttc/web/ttc-9.jpg'
  }]
}]